pietervdvn/MapComplete

assets/themes/benches/benches.json
After playing around (and actually mapping some benches :sweat_smile:), I've noticed some improvements:
1. The map starts in the middle of the ocean.
2. Most benches have the same materials and colors.
I fixed both issues now :)
I used [taginfo](https://taginfo.openstreetmap.org/tags/amenity=bench#combinations) to look for the most used (actually only used) materials and colors.
=> Improve benches theme

assets/themes/aed/aed.json
Improve french translations for theme AED.
Fix Spanish translations tagged as "en" instead of "es"
=> AED: fix french translations

assets/themes/shops/shop.svg
Removed 2 zero width no-break spaces that were at the start of the svg, causing it not to display
=> Fixed shop.svg

Docs/Making_Your_Own_Theme.md
There is a broken link in `Development_deployment.md`
=> Fix link to Tags_format.md

scripts/generateLayerOverview.ts
This fixes a problem that occurs in my personal development setup and should do no harm to others.
Background: I often use vim for editing text files. That editor creates temporary files when editing a text file, i.e. for a file named `some-theme.json` it creates a so-called swap file at `.some-theme.json.swp`. Now when I run `npm run start` the script that picks up the theme files thinks that this swap file is an actual theme file, fails to parse it and throws an error.
I think it's reasonable to check for theme files to end with `.json` instead of just containing this as a substring.
=> When filtering theme files, be a bit more strict

Customizations/JSON/TagRenderingConfigJson.ts
I came across the "type" parameter for the freeform option and was wondering which values are actually supported there. Took a moment to find that, so I think to save other theme creators some digging, let's mention that at least in a comment pointing them to the location to look it up
=> Mention supported freeform types in comment

Docs/Making_Your_Own_Theme.md
I added the link to the Matrix channel that is bridged to the Telegram group. Not sure if you left it out for a reason or just hasn't been added yet.
=> Add link to Matrix channel on Element

package.json
`npm run start` references `assets/tagRendering/*.json` but the folder does not exist. However, `assets/tagRenderings` does.
=> package.json: Fix folder name

langs/nl.json
This implies opening hours are for a business. But the opening hours syntax is shown for other things as well
=> removed "deze zaak"

assets/themes/sidewalks/sidewalks.json
In the hierarchy, unclassified highways are between residential and tertiary / secondary, which are already considered in the theme.
=> Add unclassified highways to Sidewalks theme

assets/layers/barrier/barrier.json
This replaces all references to the niche tag cycle_barrier:type with the approved tag cycle_barrier in the barrier layer.
Fix #610
=> Use approved tag cycle_barrier in the barrier layer

UI/BigComponents/UserBadge.ts
Hello,
This is a very small change to improve the alignment of the icons in the top right.
I noticed that the alignment was off because the gear icon was in a div.
Now it's not in a div and looks much better.
Before:
After:
=> improve alignment of icons

Logic/Osm/ChangesetHandler.ts
Extend the value of the changeset tag host key to include the full url of the editor. This way a reader of the changeset can open the editor based on this value. 
Example current changeset: https://www.openstreetmap.org/changeset/113127802
Example iD changeset with a clickable link that leads to the editor https://www.openstreetmap.org/changeset/117492192
---
Sitenote: I just did the same at https://github.com/zlant/parking-lanes/pull/90
=> Changeset tag `host`: Add domain and path

.gitignore
I am sad that https://github.com/pietervdvn/MapComplete/pull/721 was closed, but hope that this change is possible to make working with VS Code easier.  #ContributorExperienceMatters
---
=> Add `/.vscode` to `.gitignore`

assets/layers/surveillance_camera/surveillance_camera.json
1. Fixed typo (one -> on)
2. Added camera:mount=street_lamp because it's the fourth most used tag and shown on the wiki
3. Added camera:mount=tree because it's a logical tag that can be used quite a number of times in my vicinity (not often used though)
=> Fixed typo and added additional mounting options for surveillance_camera layer

assets/layers/drinking_water/drinking_water.json
Add alternative tag for identifying the drinking water sources "drinking_water"="yes". The restriction on "man_made" prevents undercover reservoirs to be shown, which most probably do not allow to tap water from them.
=> Add alternative drinking water tag

assets/themes/onwheels/onwheels.json
- Entrance filter to be able to show only entrances with width info on them
- (NOT WORKING: I still have all the kerb filters instead of the ones in override) Kerb override filter to be able to only filter by type raised, lowered, flush or any
- Set start zoom to 17
- Set lat and lon to Herman Teirlinckgebouw, Brussel
- Show when on zoom 19 in: elevators, reception desks, toilets, kerbs and entrances
- Override name to null and shownByDefault to false in: bike_repair_station, bike_shop, pedestrian_path, cycleways_and_roads and picnic_table
=> added a bunch of stuff (changes in pr)

Docs/Development_deployment.md
Improve the docs for an initial run of the server locally.
- the path to tool-versions was wrong
- mention that python3 is needed
- clean up the markdown a bit
I don't mind squashing these commits
=> Improve developer documentation for initial set up

assets/layers/shops/shops.json
Soft deletion of shops should be "disused:shop" instead of "disused:amenity".
=> Fix shop softdeletion

assets/layers/etymology/etymology.json
"Weg" (way) is a common suffix in street names in Germany.
See #1024.
=> etymology: add "Weg" to postfixes that get removed

assets/layers/maproulette/maproulette.json, assets/layers/maproulette_challenge/maproulette_challenge.json
Should prevent the MapRoulette Icon from showing on other layers by using a different source
=> Maproulette Icon showing on other layers

UI/Wikipedia/WikidataPreviewBox.ts
hey , me again
option might not be defined... so we need to protect against that or it breaks
=> fix: correct maybe missing option in etymology layer

package.json
not a big deal, but it's recommended that package.json use https://spdx.org/licenses/ as identifier for license...
so i've updated here
=> chore: correct license to a valid spdx identifier

Docs/Layers/all_streets.md, Docs/Layers/fietsstraat.md, Docs/Layers/toekomstige_fietsstraat.md, Docs/TagInfo/mapcomplete_cyclestreets.json, assets/themes/cyclestreets/cyclestreets.json, langs/themes/en.json, langs/themes/ja.json
I bluntly `grep`ed for all instances of cyclstreet and renamed those to cyclestreet.
I guess some files might be automatically generated, so I might have
overdone it :)
=> Typo fix: cyclstreet to cyclestreet

assets/layers/parking_spaces/parking_spaces.json, assets/themes/onwheels/onwheels.json
Enlarges icon for parking space, adds iconbadge to highlight the fact that it is a disabled space, now looks like this: ![new parking space rendering](https://user-images.githubusercontent.com/1395345/209569726-714876b7-7f08-47ec-be42-9fe42f40474f.png) 
Also changes the parking icons to be smaller for parking lots without disabled parking, to emphasize the parking lots that have disabled parking.
Before:
After:
=> More tweaks to OnWheels parking

UI/Base/Hotkeys.ts
Also activate textElementSelected when a textarea is selected, also removes the console.log
=> Include textarea in hotkey checks, remove logging

assets/layers/shops/shops.json
This would be a stationery shop, with an "e", not an "a."
=> Query typo fix.

assets/layers/bike_shop/bike_shop.json
This addresses the following points from #1387 : 
- adds service:bicycle:diy as a filter 
- adds service:bicycle:second_hand
It does not include service:bicycle:ebike_maintenance for reasons to be outlined in the issue.
=> Added filters for second hand bicycles and DIY repair to bike_shop layer.

Docs/Making_Your_Own_Theme.md
I extended the docs on how to work with a custom theme:
- Add headlines
- Hint at https://github.com/tordans/MapComplete-ThemeHelper
- Hint at lzString.compressToBase64, which took me a while to figure out today. It turns out, using different ways to encode the JSON might break at any time and other libraries seem to not be compatible with how the LZString decompress works. So I suggest to make a clear recommendation to use this one.
- Add a hint at the caching issue that might come up with the userlayout=hosted-file solution, which is why I started the ThemeHelper in the first place. Hosting it on Github Pages eg. does not really work due to caching issues.
=> Docs: Extend docs on custom theme handling, base64

.prettierrc.json
Thanks for merging https://github.com/pietervdvn/MapComplete/pull/1459 and https://github.com/pietervdvn/MapComplete/pull/1460.
Unfortunately I am still having issues locally.
a. when I run `npm run format` I am still getting a lot of files and while working on https://github.com/pietervdvn/MapComplete/pull/1463 there where a few files, especially `UI/Popup/AddNewPoint/AddNewPoint.svelte` which reformatted dramatically on safe. I disabled the auto-formatting for those files for that PR.
b. when my VS Code runs the formatter "on safe" id behaves differently from what "npm run format" does
I am not sure why, yet.
- Some changes are tue to (a)
- However, "on save" has a different opinion on where the closing bracket should go.
This PR fixes this, by updating the config.
--- …
=> Prettier: Fix new line setting

Docs/Architecture.md
Hello there👋
I have made a pull request to fix a small typo in the documentation. The word 'unchangeble' was misspelled, and I have corrected it to 'unchangeable'.
=> fixed typo in docs 'unchangeble' -> 'unchangeable'

assets/layers/questions/questions.json, assets/themes/elongated_coin/elongated_coin.json, package-lock.json, package.json, scripts/generateDocs.ts, scripts/generateTaginfoProjectFiles.ts, src/Logic/SimpleMetaTagger.ts
Adds a currency metatagger which determines the currency based on `currency:XXX` tags, as well as a default for the country. Also updates docs scripts to use `src` folder. Penny press theme is also not hidden from overview anymore, since it should now work worldwide in a reasonable way.
[Demo deploy](https://mapcomplete-git-robinlinde-patch-11-robinlinde.vercel.app/)
=> Currency metatagger, fix docs scripts

Docs/URL_Parameters.md
Wasn't clear if you're supposed to use language=dutch or language=nl
- [x ] The codebase is GPL-licensed. By opening a pull request, the new theme will be GPL too
=> Clarified that ISO 639-1 should be used for the language url parameter

src/Models/ThemeConfig/TagRenderingConfig.ts, src/UI/Map/MaplibreMap.svelte
Corrects typo 'initing'.
Ref #1904.
=> Correct typo 'initing'

assets/layers/firepit/firepit.json
Corrects typo 'firepitd'.
(Reminder: this typo propagates to the docs. Please reload them when time permits. I personally only use GitHub browser and don't/can't do any such changes directly.)
=> Correct typo 'firepitd' in firepit.json

assets/layers/sport_pitch/sport_pitch.json
This adds a decription for a horse riding arena in sport_pitch.json like this:
instead of former text "equestrian is played here".
=> Add description for horse riding arena in sport_pitch.json
