- assets/themes/aed/aed.json
I've tried to add the :fr: translation for the AED theme. Please let me know if it's the right way to do this.
> AED theme - French translation

- UI/i18n/Translations.ts
- install.bat
- run.bat
> Spanish translation

- UI/i18n/Translations.ts
Basic translation for Catalan, Spanish
> Basic translation for CA,ES

- UI/i18n/Translations.ts
Translation to Galego completed  by Galician Community
> Translation GL

- Customizations/AllKnownLayouts.ts
- README.md
- assets/themes/benches/bench_poi.svg
- assets/themes/benches/bench_public_transport.svg
- assets/themes/benches/benches.json
> Add benches theme

- assets/themes/aed/aed.json
Updated translations for AED quest to Catalan and Spanish
> Update AED to CA,ES

- UI/CustomGenerator/CustomGeneratorPanel.ts
Fix some typos and readability issues.
> Fix generator text.

- UI/FullScreenMessageBoxHandler.ts
Workaround for layout issue in Firefox because of known bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=748518
> Fix message box layout for Firefox.

- AllTranslationAssets.ts
- UI/Base/ScrollableFullScreen.ts
- UI/Popup/EditableTagRendering.ts
- UI/Popup/QuestionBox.ts
- UI/Popup/SaveButton.ts
- assets/translations.json
- css/ReviewElement.css
- css/tagrendering.css
- index.css
- tailwind.config.js
This is the first part for https://github.com/pietervdvn/MapComplete/issues/194
Right now, it has buttons for save + cancel.
Status:
- The button util classes are inspired by https://tailwindui.com/preview
- I will have to change the colors of the  primary button again, I think, once I start using it in other places of the app like the Map-Screen. This is just a first thing to get this idea going.
There are also a few other improvements int this PR that I describe in the commit messages.
> Tailwind buttons

- assets/themes/campersites/campersites.json
If you have an object with fee=yes and charge=*, you want to remove charge=* in case the user changes fee to no
> added feature to remove charge if fee=no

- assets/layers/drinking_water/drinking_water.json
> fixed spelling

- assets/translations.json
BTW, thanks for a mention!
Translations seems to be correct.
> fix double dot

- Docs/CalculatedTags.md
> Fix issues in calculated tags

- Docs/CalculatedTags.md
- Logic/ExtraFunction.ts
- Logic/SimpleMetaTagger.ts
OK, I think this is the way to properly do what I wanted to do with #268
> Fix problems in CaculatedTags.md via Typescript sources

- assets/translations.json
I found a few more issues in the translations (some strings contain a blank at the start or the end which shouldn't)
> Some translation fixes

- index.css
The answers could use some some space between the radio button and the value. How about 0.5em?
> Add some margin to the right side of the radio input of questions

- Docs/Tools/compileStats.sh
- Docs/Tools/fetchStats.sh
A few issues I found while downloading and compiling the stats. I think you'll need to check if this works on your system, too. (I'm on Linux Mint 20 here)
> Improve tools for stats fetching and compiling

- Docs/MapComplete_vs_other_editors.md
fix typos, complain about PWA a bit
> better vs SC comparison

- assets/themes/aed/aed_brugge.json
Colouring was also based on a field that has little meaning
@seppesantens, @sebkur or @chrneumann could you review and approve?
Just testing the workflow to be able to push small improvements online, even when @pietervdvn goes rollerskating again.
> improved rendering

- assets/themes/aed/aed_brugge.json
> Made the green transparent

- langs/en.json
I think this should be written like this.
(I came here from https://hosted.weblate.org/, where I aimed to translate this string to German)
Hey! Thanks for opening a pull request on Mapcomplete! This probably means you want to add a new theme - if so, please follow the checklist below.
If this pull request is for some other issue, please ignore the template.
> Suggest text update

- README.md
This presentation gives a good overview about the project. Lets link it here.
Also, some highlighting for more structure / "scannability" of the content.
> Readme: Add link to presentation about MapComplete

- assets/themes/postboxes/postboxes.json
I changed the mini-maps to be a bit bigger, and also made them less beveled and have a light gray border. I thought this looked a bit nicer and easier to read for people clicking on the postboxes and post offices.
> Postoffices postboxes minimap test

- langs/en.json
Opening hours not just used on shops and amenities
> removed amenity/shop reference

- assets/layers/barrier/barrier.json
- langs/layers/de.json
- langs/layers/en.json
- langs/layers/nl.json
Update some tags related to cycle barriers to their accepted variants.
> Update cycle_barrier tags

- .github/actions/setup-and-validate/action.yml
- .github/workflows/deploy_pietervdvn.yml
- .github/workflows/theme_validation_and_deploy.yml
- Extract common steps to separate action
- Update workflows to use setup-node@v1.4.6
> Improve GitHub actions workflows

- .github/workflows/validate-pr.yml
This makes it easier to evaluate PRs.
> Add GitHub Actions workflow to validate pull requests

- assets/themes/etymology.json
Add health, social, cultural, touristical and sport places
> Etymology - Add some public meeting places

- Docs/Making_Your_Own_Theme.md
- language
- capitalization
- code blocks
> Editorial improvements in "Making your own theme" docs

- assets/themes/etymology.json
A landuse=education can cover different education institutions.
> Etymology - Add landuse=education

- Docs/theme-template.json
There where a lot of "duplicate keys" warnings. And also a missing comma.
Ping to https://github.com/pietervdvn/MapComplete/issues/707.
---
> Fix validation issues with the theme-template

- assets/layers/bicycle_rental/bicycle_rental.json
added bike helmets as rental type
> Cycle types

- assets/layers/etymology/etymology.json
Very small addition of "lei" to the "removePostfixes"
> Small update etymology.json

- assets/layers/recycling/recycling.json
- assets/layers/waste_basket/waste_basket.json
- assets/layers/waste_disposal/waste_disposal.json
- assets/themes/waste/waste.json
I have added italian translation for waste, waste disposal and related.
> Added italian translations for waste

- .gitignore
- .gitpod.yml
- .vscode/extensions.json
- .vscode/settings.json
- .vscode/tasks.json
Gitpod and vscode settings, should also work in combination with GitHub codespaces
> Gitpod vscode

- assets/layers/pharmacy/license_info.json
- assets/layers/pharmacy/pharmacy.json
- assets/layers/pharmacy/pharmacy.svg
- assets/pharmacy/license_info.json
- assets/pharmacy/pharmacy.json
- assets/pharmacy/pharmacy.svg
- assets/themes/mapcomplete-changes/mapcomplete-changes.json
- assets/themes/pharmacies/pharmacies.json
> added pharmacy theme and layer

- assets/layers/rainbow_crossings/rainbow_crossings.json
- assets/themes/rainbow_crossings/license_info.json
- assets/themes/rainbow_crossings/logo.svg
- assets/themes/rainbow_crossings/rainbow_crossings.json
> New feature request: rainbow-crossings

- assets/layers/pharmacy/pharmacy.json
Fixes #966, also adds name label
> Added name label and opening hours icon/filter

- assets/layers/hackerspace/hackerspace.json
* Use correct path to tool-versions
Signed-off-by: Robbert Gurdeep Singh <git@beardhatcode.be>
* Add python3 to install steps
Signed-off-by: Robbert Gurdeep Singh <git@beardhatcode.be>
* Use consistent markdown
Signed-off-by: Robbert Gurdeep Singh <git@beardhatcode.be>
* Mention that nix-env is for Nix users
Signed-off-by: Robbert Gurdeep Singh <git@beardhatcode.be>
* Add note on how to install python3
Signed-off-by: Robbert Gurdeep Singh <git@beardhatcode.be>Opening a pull request on MapComplete …
> Add "images" to hackerspace.json

- assets/layers/cafe_pub/cafe_pub.json
- assets/layers/food/food.json
- assets/layers/hotel/hotel.json
- assets/layers/shops/shops.json
- assets/tagRenderings/questions.json
- langs/shared-questions/en.json
- langs/shared-questions/nl.json
- Creates some standard questions about internet access (type, fee, SSID)
- Adds it to food, cafes and pubs, hotel layers
- Map Telekom as mapping for SSID in Germany
Should fix #967
> Add questions about internet access

- assets/layers/parking/parking.json
- assets/layers/parking_spaces/license_info.json
- assets/layers/parking_spaces/parking_space.svg
- assets/layers/parking_spaces/parking_spaces.json
- assets/themes/parkings/parkings.json
Adds a layer to the parking theme showing individual parking spaces. Includes a TagRendering for the parking space type.
> Add parking spaces layer

- package.json
Hey 👋 
as the installation breaks on osx, 
here is a little fix that i think is compatible
> fix: correct sed command to be OSX compatible

- assets/layers/cycleways_and_roads/cycleways_and_roads.json
Trying to improve cycle infra .
Closes #1052 
color is debatable ofc but black pictures correctly the sadness of a street without cycleway 😄
> feat: add color for streets with no cycleways

- Logic/ImageProviders/Imgur.ts
- Logic/State/UserRelatedState.ts
- package-lock.json
- package.json
let's try to make one deps less...
jquery is quite deprecated, not used, there's not much reason to use...
i think it kinda works but in local i have 429 (i think its normal, right?)
> chore(deps): remove jquery as deps

- .github/workflows/deploy_pietervdvn.yml
- scripts/build.sh
let's make preview env more visible ...
(next we can use deploy env for staging & prod)
> chore(pr): add a preview comment on PR if they are previewable

- UI/Base/SubtleButton.ts
- UI/BigComponents/MoreScreen.ts
- css/index-tailwind-output.css
- index.css
- tailwind.config.js
as discuss in #1061 
there where some deprecations, here are the change for them... 
again don't think it breaks anything... but with css you never know 😅
> chore: remove deprecations following tailwind update

- .git-blame-ignore-revs
little expected followup for #1057 .... 
this is needed to avoid polluting the blame....
> chore: add prettier to blame ignore

- assets/themes/bag/bag.json
- assets/themes/grb/grb.json
- assets/themes/mapcomplete-changes/mapcomplete-changes.json
- test/Logic/OSM/Actions/ReplaceGeometryAction.spec.ts
This PR should fix the build, and update some old references
> Fix build, update some references

- assets/layers/atm/atm.json
- assets/layers/defibrillator/defibrillator.json
- assets/layers/ticket_validator/ticket_validator.json
- assets/layers/toilet/toilet.json
- assets/tagRenderings/questions.json
- langs/layers/en.json
- langs/shared-questions/nl.json
Fixes calculatedTags for AED theme, add some more questions to the ATM theme and uses the split out payment methods for toilets.
[Demo](https://mapcomplete-cg03vtivo-robinlinde.vercel.app/)
> Change and add questions

- assets/layers/waste_basket/waste_basket.json
> Fix "thrash" typo in English text

- UI/BigComponents/CopyrightPanel.ts
Correct Mastodon URL to MapComplete profile
> Correct Mastodon URL

- assets/layers/cafe_pub/cafe_pub.json
- assets/layers/food/food.json
- langs/layers/da.json
- langs/layers/de.json
- langs/layers/en.json
- langs/layers/es.json
- langs/layers/fr.json
- langs/layers/nl.json
Adds a question and filter to restaurants for reservation, generalizes name question for `food` and `cafe_pub` layer. Should fix #1234
> Add reservation question, fix name question(s)

- assets/layers/windturbine/windturbine.json
> Added fixme question to Windturbine layer

- assets/layers/fitness_station/fitness_station.json
fixes https://github.com/pietervdvn/MapComplete/issues/1262
> add picture to fitness_station layer

- assets/layers/barrier/barrier.json
> Only ask details for barrier if node is part of a way

- langs/en.json
Fix sentence construction grammar.
> Fix English grammatical tense.

- assets/layers/hydrant/hydrant.json
Allowed giving information about the amount of couplings with the "couplings=*" tag
> Updated hydrant layer

- assets/layers/bicycle_rental/bicycle_rental.json
- assets/layers/bike_shop/bike_shop.json
Minor text improvements, to help improve contributor experience (in English, at least.)
> minor text improvement

- UI/BigComponents/HiddenThemeList.svelte
- UI/BigComponents/ThemesList.svelte
Hidden theme buttons aren't working, this should fix it.
> fix: hidden theme link not working

- Docs/MapComplete_vs_other_editors.md
For now it is a bit limited (only shop overlay) but more is coming
> StreetComplete now can add new points

- assets/layers/cafe_pub/cafe_pub.json
> GH-1404: fix typos

- assets/layers/surveillance_camera/surveillance_camera.json
Now ! Sorry, next time we'll try weblate.
> Spanish translation added and fix typo

- UI/Base/BackButton.svelte
- UI/Base/FromHtml.svelte
- UI/Base/LoginButton.svelte
- UI/Base/MapControlButton.svelte
- UI/Base/NextButton.svelte
- UI/Base/SubtleButton.svelte
- UI/Base/SubtleLink.svelte
- UI/Base/TabbedGroup.svelte
- UI/BigComponents/ThemeButton.svelte
- UI/BigComponents/ThemeIntroPanel.svelte
- UI/InputElement/Helpers/FloorSelector.svelte
- UI/Popup/AddNewPoint/AddNewPoint.svelte
- UI/Popup/DeleteFlow/DeleteWizard.svelte
- UI/Popup/TagRendering/TagRenderingAnswer.svelte
- UI/Popup/TagRendering/TagRenderingMapping.svelte
- UI/Popup/TagRendering/TagRenderingMappingInput.svelte
- UI/Popup/TagRendering/TagRenderingQuestion.svelte
- package-lock.json
- package.json
This closes https://github.com/pietervdvn/MapComplete/issues/1461
> Introduce tailwind merge package

- assets/themes/atm/atm.json
> Update atm.json: increase merge range

- assets/layers/waste_basket/waste_basket.json
> Add waste=paper to waste basket

- Docs/Architecture.md
- Docs/CalculatedTags.md
- Docs/LanguagePicker.md
- Docs/Layers/all_vending_machine.md
- Docs/SpecialRenderings.md
- Docs/Sponsors.md
- Docs/URL_Parameters.md
> Update docs and fix som typo.

- README.md
Adds matrix logo, splits liberapay badge (buttons are separated by a space).
(leaving matrix logo blank occasionally loads a broken logo.)
> Change badge style in README.md

- assets/layers/bbq/bbq.json
- assets/layers/firepit/firepit.json
- assets/themes/fireplace/fireplace.json
new theme for fireplaces (firepits and bbq)
> fireplace.json

- CONTRIBUTING.md
- assets/layers/bench/bench.json
> Add `armchair` question to bench layer

- assets/layers/indoors/indoors.json
Adds room=printer (without proper icon)
Fixes #2131
> Update indoors.json - Add Copy Room

- assets/layers/sports_centre/sports_centre.json
Add question to asks for sports that are played at a sports_centre venue
> Add question to define which sports are played at a sports centre

- src/UI/BigComponents/MenuDrawer.svelte
> Fix missing import

- assets/layers/waste_basket/waste_basket.json
- assets/layers/waste_disposal/waste_disposal.json
- assets/themes/postboxes/postboxes.json
- assets/themes/waste/waste.json
This should fix #2279, and some similar issues.
> Remove minZoomVisible in some themes

- README.md
Add closing bracket to analytics link.
> Update README.md - Correct analytics link formatting
